version: "3.1"
volumes:
    python:
services:
    db:
        image: postgres:10-alpine
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=menuvotedb
            - POSTGRES_USER=devadmin
            - POSTGRES_PASSWORD=Ninja6708
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        command: sh -c "sleep 1 && python manage.py runserver 0.0.0.0:8000"
        ports:
            - 8000:8000
            - 3001:3001
        env_file:
            -   .env
        depends_on:
            - db